thingsboard:
  #host: "${TB_HOST}"
  #port: ${TB_PORT}
  #host: 52.82.110.11
  #port: 32534
  host: localhost
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  security:
    #caCert: "${TB_CREDENTIALS}"
    #accessToken: "${GATEWAY_TOKEN}"
    accessToken: Ns6ineFDO4uaRTomkkzl
    #accessToken: lR1MkxXoSJzOCRhSnUwI
  qos: 0
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    #configuration: "${CONFIG_FILE}"
    configuration: mqtt.json

