thingsboard:
  host: digital-dev.kukaplus.com
  port: 32534
  remoteShell: false
  remoteConfiguration: false
  security:
#    caCert: "/Users/gongshengwei/workspace/docker/gateway/gtcfg/certificate.pem"
    accessToken: lR1MkxXoSJzOCRhSnUwI
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json

