thingsboard:
  host: "${TB_HOST}"
  port: "${TB_PORT}"
  remoteShell: false
  remoteConfiguration: false
  security:
    caCert: "${TB_CREDENTIALS}"
    accessToken: "${GATEWAY_TOKEN}"
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: "${CONFIG_FILE}"

